### ISSUE TITLE
Metadata translation progress

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-ij#36]
Keeping track of progress on metadata translations here
https://github.com/saalfeldlab/n5-ij/tree/translation-metadata

Some of this work may move to n5-imglib2

### Ideas for consideration
* implement a dataset-wise translation that does not require operating on the entire tree

### TODOs
- [x] Make `CanonicalMetadataParser` that removes translation functionality from [`TranslatedTreeMetadataParser`](https://github.com/saalfeldlab/n5-ij/blob/translation-metadata/src/main/java/org/janelia/saalfeldlab/n5/metadata/canonical/TranslatedTreeMetadataParser.java) (https://github.com/saalfeldlab/n5-ij/commit/70ac4aadc5f1abb018d823446de2efd2bad6f8a7)
- [x] Make `CanonicalMetadata` an interface and simplify (d6603bc )
   - [x] Simplify [deserializer](https://github.com/saalfeldlab/n5-ij/blob/translation-metadata/src/main/java/org/janelia/saalfeldlab/n5/metadata/canonical/CanonicalMetadata.java#L56) to be more like [transform deserializer](https://github.com/saalfeldlab/n5-ij/blob/translation-metadata/src/main/java/org/janelia/saalfeldlab/n5/metadata/transforms/SpatialTransformAdapter.java) in that it can return one of several subclasses (
d6603bc )

**Comment by bogovicj** [comment]
see https://github.com/saalfeldlab/n5-imglib2/pull/28

**Comment by bogovicj** [comment]
[n5-imglib2 4.2.0 released ](https://github.com/saalfeldlab/n5-imglib2/releases/tag/n5-imglib2-4.2.0)
and
https://github.com/saalfeldlab/n5-ij/pull/41 merged
closing
